local M = {}

function M.get(p)
  return {
    -- ── Editor base ──────────────────────────────────────────────────────────
    Normal            = { fg = p.fg,          bg = p.bg },
    NormalFloat       = { fg = p.fg,          bg = p.bg_float },
    NormalNC          = { fg = p.fg_dim,      bg = p.bg },
    Cursor            = { fg = p.bg,          bg = p.fg },
    CursorLine        = { bg = p.cursor_line },
    CursorColumn      = { bg = p.cursor_line },
    CursorLineNr      = { fg = p.cur_line_nr, bold = true },
    LineNr            = { fg = p.line_nr },
    SignColumn        = { fg = p.line_nr,     bg = p.bg },
    ColorColumn       = { bg = p.cursor_line },

    Visual            = { bg = p.bg_visual },
    VisualNOS         = { bg = p.bg_visual },

    Search            = { fg = p.bg,  bg = p.keyword },
    IncSearch         = { fg = p.bg,  bg = p.warning },
    CurSearch         = { fg = p.bg,  bg = p.keyword, bold = true },
    Substitute        = { fg = p.bg,  bg = p.warning },

    -- ── Window chrome ────────────────────────────────────────────────────────
    StatusLine        = { fg = p.status_fg,  bg = p.status_bg },
    StatusLineNC      = { fg = p.line_nr,    bg = p.bg_alt },
    WinSeparator      = { fg = p.border },
    FloatBorder       = { fg = p.border,     bg = p.bg_float },
    FloatTitle        = { fg = p.keyword,    bg = p.bg_float, bold = true },
    FloatFooter       = { fg = p.comment,    bg = p.bg_float },

    TabLine           = { fg = p.line_nr,    bg = p.bg_alt },
    TabLineSel        = { fg = p.fg,         bg = p.bg, bold = true },
    TabLineFill       = { bg = p.bg_alt },

    -- ── Popup menu ───────────────────────────────────────────────────────────
    Pmenu             = { fg = p.fg,         bg = p.pmenu_bg },
    PmenuSel          = { fg = p.fg,         bg = p.pmenu_sel, bold = true },
    PmenuSbar         = { bg = p.pmenu_sbar },
    PmenuThumb        = { bg = p.pmenu_thumb },
    PmenuMatch        = { fg = p.keyword,    bold = true },
    PmenuMatchSel     = { fg = p.keyword,    bg = p.pmenu_sel, bold = true },
    PmenuKind         = { fg = p.info,       bg = p.pmenu_bg },
    PmenuKindSel      = { fg = p.info,       bg = p.pmenu_sel },
    PmenuExtra        = { fg = p.comment,    bg = p.pmenu_bg },
    PmenuExtraSel     = { fg = p.comment,    bg = p.pmenu_sel },

    -- ── Folds / misc ─────────────────────────────────────────────────────────
    Folded            = { fg = p.comment,    bg = p.bg_alt, italic = true },
    FoldColumn        = { fg = p.line_nr,    bg = p.bg },
    NonText           = { fg = p.line_nr },
    EndOfBuffer       = { fg = p.bg },
    SpecialKey        = { fg = p.info },
    Whitespace        = { fg = p.line_nr },
    MatchParen        = { fg = p.keyword,    bold = true, underline = true },
    Conceal           = { fg = p.comment },
    Directory         = { fg = p.func,       bold = true },
    Title             = { fg = p.keyword,    bold = true },

    -- ── Messages ─────────────────────────────────────────────────────────────
    ErrorMsg          = { fg = p.error,      bold = true },
    WarningMsg        = { fg = p.warning },
    ModeMsg           = { fg = p.fg,         bold = true },
    MoreMsg           = { fg = p.info },
    Question          = { fg = p.info },

    -- ── Diff ─────────────────────────────────────────────────────────────────
    DiffAdd           = { bg = p.bg_diff_add },
    DiffDelete        = { fg = p.removed,    bg = p.bg_diff_del },
    DiffChange        = { bg = p.bg_diff_chg },
    DiffText          = { fg = p.changed,    bg = p.bg_diff_chg, bold = true },
    Added             = { fg = p.added },
    Removed           = { fg = p.removed },
    Changed           = { fg = p.changed },

    -- ── Syntax (classic) ─────────────────────────────────────────────────────
    Comment           = { fg = p.comment,    italic = true },

    Constant          = { fg = p.constant },
    String            = { fg = p.string },
    Character         = { fg = p.string },
    Number            = { fg = p.number },
    Float             = { fg = p.number },
    Boolean           = { fg = p.constant,   bold = true },

    Identifier        = { fg = p.variable },
    Function          = { fg = p.func,       bold = true },

    Statement         = { fg = p.keyword },
    Conditional       = { fg = p.keyword,    bold = true },
    Repeat            = { fg = p.keyword,    bold = true },
    Label             = { fg = p.keyword },
    Operator          = { fg = p.operator },
    Keyword           = { fg = p.keyword,    bold = true },
    Exception         = { fg = p.keyword,    bold = true },

    PreProc           = { fg = p.type },
    Include           = { fg = p.keyword },
    Define            = { fg = p.keyword },
    Macro             = { fg = p.constant },
    PreCondit         = { fg = p.keyword },

    Type              = { fg = p.type,       bold = true, italic = true },
    StorageClass      = { fg = p.type,       italic = true },
    Structure         = { fg = p.type,       italic = true },
    Typedef           = { fg = p.type,       bold = true, italic = true },

    Special           = { fg = p.constant },
    SpecialChar       = { fg = p.string },
    Tag               = { fg = p.tag },
    Delimiter         = { fg = p.punctuation },
    SpecialComment    = { fg = p.comment,    bold = true },
    Debug             = { fg = p.warning },

    Underlined        = { underline = true },
    Ignore            = { fg = p.line_nr },
    Error             = { fg = p.error,      bold = true },
    Todo              = { fg = p.bg,         bg = p.keyword, bold = true },

    -- ── Treesitter ───────────────────────────────────────────────────────────
    ["@variable"]                    = { fg = p.variable },
    ["@variable.builtin"]            = { fg = p.constant,    bold = true },
    ["@variable.parameter"]          = { fg = p.parameter,   italic = true },
    ["@variable.parameter.builtin"]  = { fg = p.constant,    italic = true },
    ["@variable.member"]             = { fg = p.property },

    ["@constant"]                    = { fg = p.constant },
    ["@constant.builtin"]            = { fg = p.constant,    bold = true },
    ["@constant.macro"]              = { fg = p.constant },

    ["@string"]                      = { fg = p.string },
    ["@string.escape"]               = { fg = p.keyword },
    ["@string.special"]              = { fg = p.constant },
    ["@string.regexp"]               = { fg = p.number },
    ["@string.special.path"]         = { fg = p.func,        underline = true },
    ["@string.special.url"]          = { fg = p.info,        underline = true },

    ["@character"]                   = { fg = p.string },
    ["@number"]                      = { fg = p.number },
    ["@number.float"]                = { fg = p.number },
    ["@boolean"]                     = { fg = p.constant,    bold = true },

    ["@function"]                    = { fg = p.func,        bold = true },
    ["@function.builtin"]            = { fg = p.func },
    ["@function.call"]               = { fg = p.func },
    ["@function.macro"]              = { fg = p.constant },
    ["@function.method"]             = { fg = p.func,        bold = true },
    ["@function.method.call"]        = { fg = p.func },

    ["@constructor"]                 = { fg = p.type },
    ["@operator"]                    = { fg = p.operator },

    ["@keyword"]                     = { fg = p.keyword,     bold = true },
    ["@keyword.return"]              = { fg = p.keyword,     bold = true },
    ["@keyword.import"]              = { fg = p.keyword },
    ["@keyword.type"]                = { fg = p.type,        bold = true },
    ["@keyword.modifier"]            = { fg = p.keyword },
    ["@keyword.repeat"]              = { fg = p.keyword,     bold = true },
    ["@keyword.exception"]           = { fg = p.keyword,     bold = true },
    ["@keyword.conditional"]         = { fg = p.keyword,     bold = true },
    ["@keyword.conditional.ternary"] = { fg = p.operator },
    ["@keyword.directive"]           = { fg = p.type },
    ["@keyword.coroutine"]           = { fg = p.keyword,     bold = true },

    ["@type"]                        = { fg = p.type,        italic = true },
    ["@type.builtin"]                = { fg = p.type,        bold = true, italic = true },
    ["@type.definition"]             = { fg = p.type,        bold = true, italic = true },
    ["@type.qualifier"]              = { fg = p.keyword },

    ["@attribute"]                   = { fg = p.attribute },
    ["@attribute.builtin"]           = { fg = p.attribute,   bold = true },
    ["@property"]                    = { fg = p.property },
    ["@namespace"]                   = { fg = p.namespace },
    ["@module"]                      = { fg = p.namespace },
    ["@module.builtin"]              = { fg = p.constant,    bold = true },
    ["@label"]                       = { fg = p.keyword },

    ["@punctuation.delimiter"]       = { fg = p.punctuation },
    ["@punctuation.bracket"]         = { fg = p.punctuation },
    ["@punctuation.special"]         = { fg = p.keyword },

    ["@comment"]                     = { fg = p.comment,     italic = true },
    ["@comment.documentation"]       = { fg = p.info,        italic = true },
    ["@comment.error"]               = { fg = p.error,       bold = true },
    ["@comment.warning"]             = { fg = p.warning,     bold = true },
    ["@comment.todo"]                = { fg = p.bg,          bg = p.keyword, bold = true },
    ["@comment.note"]                = { fg = p.info,        bold = true },

    -- Markup (Markdown, RST, etc.)
    ["@markup.heading"]              = { fg = p.keyword,     bold = true },
    ["@markup.heading.1"]            = { fg = p.keyword,     bold = true },
    ["@markup.heading.2"]            = { fg = p.type,        bold = true },
    ["@markup.heading.3"]            = { fg = p.func,        bold = true },
    ["@markup.heading.4"]            = { fg = p.string,      bold = true },
    ["@markup.heading.5"]            = { fg = p.comment,     bold = true },
    ["@markup.heading.6"]            = { fg = p.comment },
    ["@markup.link"]                 = { fg = p.info,        underline = true },
    ["@markup.link.label"]           = { fg = p.string },
    ["@markup.link.url"]             = { fg = p.info,        underline = true },
    ["@markup.raw"]                  = { fg = p.string,      bg = p.bg_alt },
    ["@markup.raw.block"]            = { fg = p.string,      bg = p.bg_alt },
    ["@markup.italic"]               = { italic = true },
    ["@markup.strong"]               = { bold = true },
    ["@markup.strikethrough"]        = { strikethrough = true },
    ["@markup.list"]                 = { fg = p.keyword },
    ["@markup.list.checked"]         = { fg = p.added },
    ["@markup.list.unchecked"]       = { fg = p.comment },
    ["@markup.quote"]                = { fg = p.comment,     italic = true },
    ["@markup.math"]                 = { fg = p.number },

    ["@tag"]                         = { fg = p.tag },
    ["@tag.attribute"]               = { fg = p.attribute,   italic = true },
    ["@tag.delimiter"]               = { fg = p.punctuation },
    ["@tag.builtin"]                 = { fg = p.tag,         bold = true },

    ["@diff.plus"]                   = { fg = p.added },
    ["@diff.minus"]                  = { fg = p.removed },
    ["@diff.delta"]                  = { fg = p.changed },

    -- ── LSP semantic tokens ───────────────────────────────────────────────────
    ["@lsp.type.class"]              = { fg = p.type,        bold = true,  italic = true },
    ["@lsp.type.decorator"]          = { fg = p.attribute },
    ["@lsp.type.enum"]               = { fg = p.type,        italic = true },
    ["@lsp.type.enumMember"]         = { fg = p.constant },
    ["@lsp.type.function"]           = { fg = p.func },
    ["@lsp.type.interface"]          = { fg = p.type,        italic = true },
    ["@lsp.type.macro"]              = { fg = p.constant },
    ["@lsp.type.method"]             = { fg = p.func },
    ["@lsp.type.namespace"]          = { fg = p.namespace },
    ["@lsp.type.parameter"]          = { fg = p.parameter,   italic = true },
    ["@lsp.type.property"]           = { fg = p.property },
    ["@lsp.type.struct"]             = { fg = p.type,        italic = true },
    ["@lsp.type.type"]               = { fg = p.type,        italic = true },
    ["@lsp.type.typeParameter"]      = { fg = p.type,        italic = true },
    ["@lsp.type.variable"]           = { fg = p.variable },
    ["@lsp.type.keyword"]            = { fg = p.keyword },
    ["@lsp.type.comment"]            = { fg = p.comment,     italic = true },
    ["@lsp.type.string"]             = { fg = p.string },
    ["@lsp.type.number"]             = { fg = p.number },
    ["@lsp.type.operator"]           = { fg = p.operator },
    ["@lsp.type.event"]              = { fg = p.type },

    -- ── Diagnostics ──────────────────────────────────────────────────────────
    DiagnosticError                  = { fg = p.error },
    DiagnosticWarn                   = { fg = p.warning },
    DiagnosticInfo                   = { fg = p.info },
    DiagnosticHint                   = { fg = p.hint },
    DiagnosticOk                     = { fg = p.added },

    DiagnosticUnderlineError         = { underline = true, sp = p.error },
    DiagnosticUnderlineWarn          = { underline = true, sp = p.warning },
    DiagnosticUnderlineInfo          = { underline = true, sp = p.info },
    DiagnosticUnderlineHint          = { underline = true, sp = p.hint },

    DiagnosticVirtualTextError       = { fg = p.error,   italic = true },
    DiagnosticVirtualTextWarn        = { fg = p.warning, italic = true },
    DiagnosticVirtualTextInfo        = { fg = p.info,    italic = true },
    DiagnosticVirtualTextHint        = { fg = p.hint,    italic = true },

    DiagnosticSignError              = { fg = p.error },
    DiagnosticSignWarn               = { fg = p.warning },
    DiagnosticSignInfo               = { fg = p.info },
    DiagnosticSignHint               = { fg = p.hint },

    DiagnosticFloatingError          = { fg = p.error },
    DiagnosticFloatingWarn           = { fg = p.warning },
    DiagnosticFloatingInfo           = { fg = p.info },
    DiagnosticFloatingHint           = { fg = p.hint },

    -- ── LSP ──────────────────────────────────────────────────────────────────
    LspReferenceText                 = { bg = p.bg_visual },
    LspReferenceRead                 = { bg = p.bg_visual },
    LspReferenceWrite                = { bg = p.bg_visual, bold = true },
    LspInlayHint                     = { fg = p.hint, bg = p.bg_alt, italic = true },
    LspSignatureActiveParameter      = { fg = p.keyword, bold = true, underline = true },
    LspCodeLens                      = { fg = p.comment, italic = true },
    LspCodeLensSeparator             = { fg = p.line_nr },

    -- ── Telescope ────────────────────────────────────────────────────────────
    TelescopeNormal                  = { fg = p.fg,       bg = p.bg_float },
    TelescopeBorder                  = { fg = p.border,   bg = p.bg_float },
    TelescopePromptNormal            = { fg = p.fg,       bg = p.pmenu_bg },
    TelescopePromptBorder            = { fg = p.border,   bg = p.pmenu_bg },
    TelescopePromptTitle             = { fg = p.bg,       bg = p.keyword,  bold = true },
    TelescopePreviewTitle            = { fg = p.bg,       bg = p.info,     bold = true },
    TelescopeResultsTitle            = { fg = p.border,   bg = p.bg_float },
    TelescopeMatching                = { fg = p.keyword,  bold = true },
    TelescopeSelection               = { bg = p.pmenu_sel },
    TelescopeSelectionCaret          = { fg = p.keyword,  bg = p.pmenu_sel },
    TelescopeMultiSelection          = { fg = p.type,     bg = p.pmenu_sel },
    TelescopePreviewLine             = { bg = p.bg_visual },

    -- ── nvim-tree ────────────────────────────────────────────────────────────
    NvimTreeNormal                   = { fg = p.fg,       bg = p.bg_alt },
    NvimTreeNormalNC                 = { fg = p.fg_dim,   bg = p.bg_alt },
    NvimTreeFolderIcon               = { fg = p.info },
    NvimTreeFolderName               = { fg = p.func },
    NvimTreeOpenedFolderName         = { fg = p.func,     bold = true },
    NvimTreeRootFolder               = { fg = p.keyword,  bold = true },
    NvimTreeSymlink                  = { fg = p.info,     underline = true },
    NvimTreeGitDirty                 = { fg = p.changed },
    NvimTreeGitNew                   = { fg = p.added },
    NvimTreeGitDeleted               = { fg = p.removed },
    NvimTreeGitStaged                = { fg = p.added },
    NvimTreeSpecialFile              = { fg = p.type,     bold = true },
    NvimTreeIndentMarker             = { fg = p.line_nr },
    NvimTreeWinSeparator             = { fg = p.border,   bg = p.bg_alt },

    -- ── GitSigns ─────────────────────────────────────────────────────────────
    GitSignsAdd                      = { fg = p.added },
    GitSignsChange                   = { fg = p.changed },
    GitSignsDelete                   = { fg = p.removed },
    GitSignsAddNr                    = { fg = p.added },
    GitSignsChangeNr                 = { fg = p.changed },
    GitSignsDeleteNr                 = { fg = p.removed },
    GitSignsAddLn                    = { bg = p.bg_diff_add },
    GitSignsChangeLn                 = { bg = p.bg_diff_chg },

    -- ── Which-key ────────────────────────────────────────────────────────────
    WhichKey                         = { fg = p.keyword },
    WhichKeyGroup                    = { fg = p.func },
    WhichKeyDesc                     = { fg = p.fg_dim },
    WhichKeySeparator                = { fg = p.punctuation },
    WhichKeyValue                    = { fg = p.string },
    WhichKeyBorder                   = { fg = p.border },
    WhichKeyNormal                   = { fg = p.fg,       bg = p.bg_float },

    -- ── Indent Blankline ─────────────────────────────────────────────────────
    IblIndent                        = { fg = p.bg_visual },
    IblScope                         = { fg = p.border },

    -- ── Notify ───────────────────────────────────────────────────────────────
    NotifyERRORBorder                = { fg = p.error },
    NotifyWARNBorder                 = { fg = p.warning },
    NotifyINFOBorder                 = { fg = p.info },
    NotifyDEBUGBorder                = { fg = p.hint },
    NotifyTRACEBorder                = { fg = p.hint },
    NotifyERRORTitle                 = { fg = p.error,   bold = true },
    NotifyWARNTitle                  = { fg = p.warning, bold = true },
    NotifyINFOTitle                  = { fg = p.info,    bold = true },
    NotifyDEBUGTitle                 = { fg = p.hint },
    NotifyTRACETitle                 = { fg = p.hint },

    -- ── Flash / Hop ──────────────────────────────────────────────────────────
    FlashLabel                       = { fg = p.bg,      bg = p.keyword, bold = true },
    FlashCurrent                     = { fg = p.bg,      bg = p.type,    bold = true },
    FlashMatch                       = { fg = p.fg,      bg = p.bg_visual },
    HopNextKey                       = { fg = p.keyword, bold = true },
    HopNextKey1                      = { fg = p.keyword, bold = true },
    HopNextKey2                      = { fg = p.type },
    HopUnmatched                     = { fg = p.line_nr },

    -- ── nvim-cmp ─────────────────────────────────────────────────────────────
    CmpItemAbbr                      = { fg = p.fg },
    CmpItemAbbrMatch                 = { fg = p.keyword, bold = true },
    CmpItemAbbrMatchFuzzy            = { fg = p.keyword },
    CmpItemAbbrDeprecated            = { fg = p.line_nr, strikethrough = true },
    CmpItemKind                      = { fg = p.info },
    CmpItemMenu                      = { fg = p.comment },
    CmpItemKindVariable              = { fg = p.variable },
    CmpItemKindFunction              = { fg = p.func },
    CmpItemKindMethod                = { fg = p.func },
    CmpItemKindKeyword               = { fg = p.keyword },
    CmpItemKindText                  = { fg = p.fg },
    CmpItemKindSnippet               = { fg = p.string },
    CmpItemKindField                 = { fg = p.property },
    CmpItemKindProperty              = { fg = p.property },
    CmpItemKindEnum                  = { fg = p.type },
    CmpItemKindEnumMember            = { fg = p.constant },
    CmpItemKindClass                 = { fg = p.type },
    CmpItemKindStruct                = { fg = p.type },
    CmpItemKindModule                = { fg = p.namespace },
    CmpItemKindInterface             = { fg = p.type },
    CmpItemKindConstructor           = { fg = p.type },
    CmpItemKindTypeParameter         = { fg = p.type },
    CmpItemKindConstant              = { fg = p.constant },
    CmpItemKindValue                 = { fg = p.number },
    CmpItemKindUnit                  = { fg = p.number },
    CmpItemKindColor                 = { fg = p.func },
    CmpItemKindFile                  = { fg = p.fg },
    CmpItemKindFolder                = { fg = p.func },
    CmpItemKindEvent                 = { fg = p.type },
    CmpItemKindOperator              = { fg = p.operator },
    CmpItemKindReference             = { fg = p.info },

    -- ── Snacks.nvim ──────────────────────────────────────────────────────────
    SnacksIndent                     = { fg = p.bg_visual },
    SnacksIndentScope                = { fg = p.border },
    SnacksDashboardHeader            = { fg = p.keyword, bold = true },
    SnacksDashboardFooter            = { fg = p.comment, italic = true },
    SnacksDashboardTitle             = { fg = p.type,    bold = true },
    SnacksDashboardDesc              = { fg = p.fg_dim },
    SnacksDashboardKey               = { fg = p.keyword },
    SnacksDashboardIcon              = { fg = p.info },
    SnacksPickerBorder               = { fg = p.border,  bg = p.bg_float },
    SnacksPickerMatch                = { fg = p.keyword, bold = true },
    SnacksPickerSelected             = { bg = p.pmenu_sel },
    SnacksPickerDir                  = { fg = p.comment },
  }
end

return M
